### ISSUE TITLE
About test blur images ?

### ISSUE THREAD

**Issue by codeman008** [xinntao/EDVR#101]
I run tets.py then this wrong happen:
(py3_gpu) D:\aisi\EDVR-master\EDVR-master\codes> python test.py -opt=D:/aisi/EDVR-master/EDVR-master/codes/options/test/test_ESRGAN.yml
export CUDA_VISIBLE_DEVICES=0
19-09-26 17:40:21.808 - INFO:   name: RRDB_ESRGAN_x4
  suffix: None
  model: sr
  distortion: sr
  scale: 4
  crop_border: None
  gpu_ids: [0]
  datasets:[
    test_1:[
      name: set5
      mode: LQGT
      dataroot_GT: ../datasets/val_set5/Set5
      phase: test
      scale: 4
      data_type: img
    ]
  ]
  network_G:[
    which_model_G: RRDBNet
    in_nc: 3
    out_nc: 3
    nf: 64
    nb: 23
    upscale: 4
    scale: 4
  ]
  path:[
    pretrain_model_G: ../experiments/pretrained_models/EDVR_REDS_deblur_L
    root: D:\aisi\EDVR-master\EDVR-master
    results_root: D:\aisi\EDVR-master\EDVR-master\results\RRDB_ESRGAN_x4
    log: D:\aisi\EDVR-master\EDVR-master\results\RRDB_ESRGAN_x4
  ]
  is_train: False

19-09-26 17:40:21.811 - INFO: Dataset [LQGTDataset - set5] is created.
19-09-26 17:40:21.812 - INFO: Number of test images in [set5]: 3
Traceback (most recent call last):
  File "D:\aisi\EDVR-master\EDVR-master\codes\models\archs\EDVR_arch.py", line 8, in <module>
    from models.archs.dcn.deform_conv import ModulatedDeformConvPack as DCN
  File "D:\aisi\EDVR-master\EDVR-master\codes\models\archs\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv, ModulatedDeformConvPack,
  File "D:\aisi\EDVR-master\EDVR-master\codes\models\archs\dcn\deform_conv.py", line 10, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from 'models.archs.dcn' (D:\aisi\EDVR-master\EDVR-master\codes\models\archs\dcn\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 35, in <module>
    model = create_model(opt)
  File "D:\aisi\EDVR-master\EDVR-master\codes\models\__init__.py", line 9, in create_model
    from .SR_model import SRModel as M
  File "D:\aisi\EDVR-master\EDVR-master\codes\models\SR_model.py", line 7, in <module>
    import models.networks as networks
  File "D:\aisi\EDVR-master\EDVR-master\codes\models\networks.py", line 5, in <module>
    import models.archs.EDVR_arch as EDVR_arch
  File "D:\aisi\EDVR-master\EDVR-master\codes\models\archs\EDVR_arch.py", line 10, in <module>
    raise ImportError('Failed to import DCNv2 module.')
ImportError: Failed to import DCNv2 module.
what should i do?  somebody can help me????Thanks very much!

**Comment by codeman008** [comment]
somebody can help me????Thanks very much!

**Comment by dawnlh** [comment]
> somebody can help me????Thanks very much!

Have you compile DCNv2 successfully?

**Comment by dawnlh** [comment]
> somebody can help me????Thanks very much!

Have you compiled DCNv2 successfully?
