### ISSUE TITLE
Caught an error while running the test script

### ISSUE THREAD

**Issue by YooPita** [xinntao/EDVR#173]
I installed all the models, all the requirements. I run the command as indicated [here](https://github.com/xinntao/EDVR/blob/master/docs/HOWTOs.md#How-to-test-StyleGAN2)(How to test DFDNet 5). System - ubuntu 20.
The following error is thrown:
❯ python tests/test_face_dfdnet.py --upscale_factor=2 --test_path datasets/TestWhole
Traceback (most recent call last):
  File "tests/test_face_dfdnet.py", line 12, in <module>
    from basicsr.models.archs.dfdnet_arch import DFDNet
  File "/home/yoopita/inc/EDVR/basicsr/models/__init__.py", line 18, in <module>
    for file_name in model_filenames
  File "/home/yoopita/inc/EDVR/basicsr/models/__init__.py", line 18, in <listcomp>
    for file_name in model_filenames
  File "/home/yoopita/miniconda3/envs/edvr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/yoopita/inc/EDVR/basicsr/models/video_gan_model.py", line 6, in <module>
    from basicsr.models import networks as networks
  File "/home/yoopita/inc/EDVR/basicsr/models/networks.py", line 1, in <module>
    from basicsr.models.archs import _arch_modules
  File "/home/yoopita/inc/EDVR/basicsr/models/archs/__init__.py", line 16, in <module>
    for file_name in arch_filenames
  File "/home/yoopita/inc/EDVR/basicsr/models/archs/__init__.py", line 16, in <listcomp>
    for file_name in arch_filenames
  File "/home/yoopita/miniconda3/envs/edvr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/yoopita/inc/EDVR/basicsr/models/archs/stylegan2_arch.py", line 7, in <module>
    from basicsr.models.ops.fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/yoopita/inc/EDVR/basicsr/models/ops/fused_act/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/yoopita/inc/EDVR/basicsr/models/ops/fused_act/fused_act.py", line 7, in <module>
    from . import fused_act_ext
ImportError: /home/yoopita/inc/EDVR/basicsr/models/ops/fused_act/fused_act_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z17fused_bias_act_opRKN2at6TensorES2_S2_iiff

**Comment by YooPita** [comment]
error here: https://pastebin.com/QxWm9KmG
