### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by mixtresh** [xinntao/EDVR#36]
(base) t:\EDVR\codes>python test_Vid4_REDS4_with_GT2.py
19-06-15 20:53:29.080 - INFO: Data: my - ../datasets/tammy/*
19-06-15 20:53:29.081 - INFO: Padding mode: replicate
19-06-15 20:53:29.082 - INFO: Model path: ../experiments/pretrained_models/EDVR_
Vimeo90K_SR_L.pth
19-06-15 20:53:29.084 - INFO: Save images: True
19-06-15 20:53:29.085 - INFO: Flip Test: False
Traceback (most recent call last):
  File "test_Vid4_REDS4_with_GT2.py", line 284, in <module>
    main()
  File "test_Vid4_REDS4_with_GT2.py", line 177, in main
    imgs = read_seq_imgs(sub_folder)
  File "test_Vid4_REDS4_with_GT2.py", line 105, in read_seq_imgs
    imgs = np.stack(img_l, axis=0)
  File "C:\Anaconda\lib\site-packages\numpy\core\shape_base.py", line 349, in st
ack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by xinntao** [comment]
Sorry for the late reply.
It seems that you tried to stack empty array. Try to check whether it reads images to `img_l`.
