### ISSUE TITLE
lmdb image read problem

### ISSUE THREAD

**Issue by LyraWang** [xinntao/EDVR#85]
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    main()
  File "train.py", line 153, in main
    for _, train_data in enumerate(train_loader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xxx/EDVR-master/codes/data/REDS_dataset.py", line 155, in __getitem__
    img_GT = util.read_img(self.GT_env, key, (3, 720, 1280))
  File "/home/xxx/EDVR-master/codes/data/util.py", line 77, in read_img
    img = _read_img_lmdb(env, path, size)
  File "/home/xxx/EDVR-master/codes/data/util.py", line 62, in _read_img_lmdb
    img_flat = np.frombuffer(buf, dtype=np.uint8)
AttributeError: 'NoneType' object has no attribute '__buffer__'

I used the train_sharp_wval.lmdb as dataroot_GT and the train_sharp_bicubic_wval.lmdb as dataroot_LQ
and in the fucntion '_read_img_lmdb', the images read from lmdb were saved, and I found some of them are broken--maybe half of its pixels are black, and some are ok

how can I  solve this problem?

**Comment by LyraWang** [comment]
the problem is caused by missing the regroup step while using the REDS_trainval_keys.pkl which is proposed by the author
